import './globals.css'
import Header from '../components/Header'
import localFont from 'next/font/local'
import Toastify from '@/components/libraries/Toastify'


const vazirFont = localFont({
  src: '../public/vazirfont/vazir.ttf'
})



// export const metadata = {
//   title: 'Create Next App',
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={vazirFont.className}
      >
        <Header />
        {children}
        <Toastify/>
      </body>
    </html>
  );
}
